# Site settings
title: Colman Reilly
email: careilly@mac.com
description: > # this means to ignore newlines until "baseurl:"
  A corner of the web for me to post long things. Tech, martial arts, horses, development, science, politics, economics, ballet, music, arts. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.colmanreilly.com" # the base hostname & protocol for your site
twitter_username: colmanetg
github_username:  careilly

# Build settings
markdown: kramdown
